

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "8000:8000"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

volumes:
  esdata01:
